toeic_trainer_homepage:
    pattern:  /
    defaults: { _controller: TOEICTrainerBundle:Default:home }

TOEICTrainerBundle_writtendocument:
        resource: "@TOEICTrainerBundle/Resources/config/routing/writtendocument.yml"
        prefix:   /writtendocument

TOEICTrainerBundle_docholes:
        resource: "@TOEICTrainerBundle/Resources/config/routing/docholes.yml"
        prefix:   /docholes

TOEICTrainerBundle_listeningphotographs:
        resource: "@TOEICTrainerBundle/Resources/config/routing/listeningphotographs.yml"
        prefix:   /listeningphotographs

TOEICTrainerBundle_audiofile:
        resource: "@TOEICTrainerBundle/Resources/config/routing/audiofile.yml"
        prefix:   /audiofile

TOEICTrainerBundle_picturefile:
        resource: "@TOEICTrainerBundle/Resources/config/routing/picturefile.yml"
        prefix:   /picturefile

TOEICTrainerBundle_exercices:
        resource: "@TOEICTrainerBundle/Resources/config/routing/exercices.yml"
        prefix:   /exercices
