toeic_trainer_homepage:
    pattern:  /
    defaults: { _controller: TOEICTrainerBundle:Default:home }

TOEICTrainerBundle_writtendocument:
        resource: "@TOEICTrainerBundle/Resources/config/routing/writtendocument.yml"
        prefix:   /writtendocument