toeic_trainer_homepage:
    pattern:  /
    defaults: { _controller: TOEICTrainerBundle:Default:home }

TOEICTrainerBundle_writtendocument:
        resource: "@TOEICTrainerBundle/Resources/config/routing/writtendocument.yml"
        prefix:   /participate/writtendocument

TOEICTrainerBundle_docholes:
        resource: "@TOEICTrainerBundle/Resources/config/routing/docholes.yml"
        prefix:   /participate/docholes

TOEICTrainerBundle_listeningphotographs:
        resource: "@TOEICTrainerBundle/Resources/config/routing/listeningphotographs.yml"
        prefix:   /participate/listeningphotographs

TOEICTrainerBundle_answerquestion:
        resource: "@TOEICTrainerBundle/Resources/config/routing/answerquestion.yml"
        prefix:   /participate/answerquestion

TOEICTrainerBundle_audiofile:
        resource: "@TOEICTrainerBundle/Resources/config/routing/audiofile.yml"
        prefix:   /participate/audiofile

TOEICTrainerBundle_picturefile:
        resource: "@TOEICTrainerBundle/Resources/config/routing/picturefile.yml"
        prefix:   /participate/picturefile

TOEICTrainerBundle_exercices:
        resource: "@TOEICTrainerBundle/Resources/config/routing/exercices.yml"
        prefix:   /exercises

TOEICTrainerBundle_docquestions:
        resource: "@TOEICTrainerBundle/Resources/config/routing/docquestions.yml"
        prefix:   /docquestions