parameters:
#    toeic_trainer.example.class: TN\TOEICTrainerBundle\Example

services:
#    toeic_trainer.example:
#        class: %toeic_trainer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
