tn.toeic.exercices.main_page.listening:
    pattern:  /listening
    defaults: { _controller: "TOEICTrainerBundle:ListeningExercices:index" }

tn.toeic.exercices.main_page.listening.photographs:
    pattern:  /listening/photographs
    defaults: { _controller: "TOEICTrainerBundle:ListeningExercices:photographs" }

tn.toeic.exercices.main_page.listening.photographs.train:
    pattern:  /listening/photographs/train
    defaults: { _controller: "TOEICTrainerBundle:ListeningExercicesPhotographs:show" }

tn.toeic.exercices.main_page.listening.photographs.train.answer:
    pattern:  /listening/photographs/train/{id}/answer/{result}
    defaults: { _controller: "TOEICTrainerBundle:ListeningExercicesPhotographs:showAnswer" }

tn.toeic.exercices.main_page.listening.qa:
    pattern:  /listening/questions_and_answers
    defaults: { _controller: "TOEICTrainerBundle:ListeningExercices:qa" }

tn.toeic.exercices.main_page.listening.qa.train:
    pattern:  /listening/questions_and_answers/train
    defaults: { _controller: "TOEICTrainerBundle:ListeningExercicesQA:show" }

tn.toeic.exercices.main_page.listening.qa.train.answer:
    pattern:  /listening/questions_and_answers/train/{id}/answer/{result}
    defaults: { _controller: "TOEICTrainerBundle:ListeningExercicesQA:showAnswer" }

tn.toeic.exercices.main_page.listening.conversations:
    pattern:  /listening/conversations
    defaults: { _controller: "TOEICTrainerBundle:ListeningExercices:conversations" }

tn.toeic.exercices.main_page.listening.conversations.train:
    pattern:  /listening/conversations/train
    defaults: { _controller: "TOEICTrainerBundle:ListeningExercicesConversations:show" }

tn.toeic.exercices.main_page.listening.conversations.train.answer:
    pattern:  /listening/conversations/train/{id}/answer/{result}
    defaults: { _controller: "TOEICTrainerBundle:ListeningExercicesConversations:showAnswer" }

tn.toeic.exercices.main_page.listening.talks:
    pattern:  /listening/talks
    defaults: { _controller: "TOEICTrainerBundle:ListeningExercices:talks" }

tn.toeic.exercices.main_page.listening.talks.train:
    pattern:  /listening/talks/train
    defaults: { _controller: "TOEICTrainerBundle:ListeningExercicesTalks:show" }

tn.toeic.exercices.main_page.listening.talks.train.answer:
    pattern:  /listening/talks/train/{id}/answer/{result}
    defaults: { _controller: "TOEICTrainerBundle:ListeningExercicesTalks:showAnswer" }

tn.toeic.exercices.main_page.reading:
    pattern:  /reading
    defaults: { _controller: "TOEICTrainerBundle:ReadingExercices:index" }

# Reading: Word Holes in a sentence
tn.toeic.exercices.main_page.reading.inc_sentences:
    pattern:  /reading/inc_sentences
    defaults: { _controller: "TOEICTrainerBundle:ReadingExercices:inc_sentences" }

tn.toeic.exercices.main_page.reading.inc_sentences.train:
    pattern:  /reading/inc_sentences/train/exercice
    defaults: { _controller: "TOEICTrainerBundle:ReadingExercicesDocHole:showSentences" }

tn.toeic.exercices.main_page.reading.inc_sentences.train.check:
    pattern:  /reading/inc_sentences/train/grading
    defaults: { _controller: "TOEICTrainerBundle:ReadingExercicesDocHole:checkSentences" }
    requirements: { _method: post }

# Reading: Word Holes in a document
tn.toeic.exercices.main_page.reading.inc_documents:
    pattern:  /reading/inc_documents
    defaults: { _controller: "TOEICTrainerBundle:ReadingExercices:inc_documents" }

tn.toeic.exercices.main_page.reading.inc_documents.train:
    pattern:  /reading/inc_documents/train/exercice
    defaults: { _controller: "TOEICTrainerBundle:ReadingExercicesDocHole:show" }

tn.toeic.exercices.main_page.reading.inc_documents.train.check:
    pattern:  /reading/inc_documents/train/grading
    defaults: { _controller: "TOEICTrainerBundle:ReadingExercicesDocHole:check" }
    requirements: { _method: post }

# Reading: Questions/answers in a document
tn.toeic.exercices.main_page.reading.qa_documents:
    pattern:  /reading/qa_documents
    defaults: { _controller: "TOEICTrainerBundle:ReadingExercices:qa_documents" }

tn.toeic.exercices.main_page.reading.qa_documents.train:
    pattern:  /reading/qa/train/exercice
    defaults: { _controller: "TOEICTrainerBundle:ReadingExercicesQA:show" }

tn.toeic.exercices.main_page.reading.qa_documents.train.check:
    pattern:  /reading/qa/train/grading
    defaults: { _controller: "TOEICTrainerBundle:ReadingExercicesQA:check" }
    requirements: { _method: post }